services:
  - type: web
    name: control-proyectos
    env: static
    buildCommand: null
    startCommand: null
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /html/index.html
